nome = input("Olá usuario! Seja bem-vindo ao programa\nDigite o seu nome: ")
cpf = input("Agora digite o seu cpf: ")
endereco = input("Digite o seu endereco: ")
idade = int(input("Me forneça a sua idade: "))
altura = float(input("Me fale a sua altura: "))
telefone = input("Para finalizar o seu telefone: ")

print("     \nRelátorio do Usuario     ")
print("\nNome:", nome)
print("CPF:", cpf)
print("Endereço:", endereco)
print("Idade:", idade)
print("Altura:", altura)
print("Telefone:", telefone)